### ISSUE TITLE
mlbv won't start when installed in virtualenv3

### ISSUE THREAD

**Issue by JamalStevens** [kmac/mlbv#13]
(virtualenv3) aszwet1@falcon ~ $ mlbv --team chc --fetch
Traceback (most recent call last):
  File "/home/aszwet1/virtualenv3/bin/mlbv", line 11, in <module>
    sys.exit(main())
  File "/home/aszwet1/virtualenv3/lib/python3.6/site-packages/mlbam/mlbv.py", line 135, in main
    config.CONFIG = config.MLBConfig(args)
  File "/home/aszwet1/virtualenv3/lib/python3.6/site-packages/mlbam/config.py", line 158, in __init__
    Config.__init__(self, args)
  File "/home/aszwet1/virtualenv3/lib/python3.6/site-packages/mlbam/config.py", line 64, in __init__
    self.parser = self.__init_configparser(script_name)
  File "/home/aszwet1/virtualenv3/lib/python3.6/site-packages/mlbam/config.py", line 108, in __init_configparser
    parser.read_string(config_string)
  File "/usr/lib64/python3.6/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib64/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<string>' [line 57]: option '<meta name' in section 'mlbv' already exists

**Comment by aszwet1** [comment]
This happened when I tried to get mlbv started while it was running in a virtualenv.  I had to manually download the default template of the config file and put it in this directory:

/home/aszwet1/virtualenv3/lib/python3.6/site-packages/

**Comment by kmac** [comment]
Yes I just tried this with a new virtualenv and am seeing the issue... it needs a tweak to the setup.py script.
As a workaround, the easiest thing to do is to create the config file manually. Just copy the template from this repo and put it at `$HOME/.config/mlbv/config`. Then manually fill in the userid/password for mlb.tv.

**Comment by aszwet1** [comment]
Thanks I appreciate it. I will give that a try. One thing I had a question
about is how does the streamline create the output file?  Is there a way to
tweak that so that it wouldn't do a table but to creat another m3u8?

**Comment by kmac** [comment]
I'm not sure how you're accessing your remote file system.  vlc or mpv can handle files being written to at the same time, but the required metadata it needs may not be there depending on how you're mounting the remote filesystem. I believe this works fine for me if I use something like SMB or sshfs to mount the remote filesystem. If you can't use either of those you may be out of luck.

As a bit of a workaround, you could start the download at a particular inning, then let it run for half an hour and stop it. Then transfer the file over to your local system, and watch that segment. Then see where you are, and kick off another download at the top of that inning. Yeah, that's about all I can think of, and it pretty much sucks.

Since the original issue is fixed I'm going to close this off.
