### ISSUE TITLE
Couldn't find vlc

### ISSUE THREAD

**Issue by suedunham** [kmac/mlbv#21]
Had an issue setting up on Windows where it could not find the media player, in my case vlc. I can't remember the exact details, but I fixed it by adding the directory with vlc.exe to the system path.

**Comment by tonywagner** [comment]
That works, otherwise you would need to put the full path to the VLC executable in your mlbv config file. Mine is:

video_player=C:\Program Files\VideoLAN\VLC\vlc.exe

**Comment by kmac** [comment]
Thanks @tonywagner, this is one reason you can specify the full path to the player in the config file. In linux the path to vlc is usually common to the default environment; I guess this isn't the case in windows.
I'm going to close this because there's really nothing to do in the code here, other than do one of the two options as above:

1. add vlc to the system path, or
2. update the `video_player` option in config file with full path to the player
