### ISSUE TITLE
Recording during off season

### ISSUE THREAD

**Issue by ljcervantes** [kmac/mlbv#58]
$ mlbv --date 2021-04-06 -t wsh --fetch
Default (home/away) feed not found: choosing first available feed
Feed is not available: None
No stream URL found

I have made sure I had access to mlb.tv during off season but I am getting this error.

**Comment by samseborn** [comment]
I'm in the same situation too. Everything related to the video, such as archive videos and recaps, does not work. However, standing, stats, etc. are displayed. Looking at the session file, all other key values except the last one appear null.

**Comment by kmac** [comment]
MLB isn't publishing the feeds. I don't think there's anything I can do for this.

**Comment by ljcervantes** [comment]
Crazy..  Thanks for looking into it.  Really enjoy mlbv!

**Comment by tonywagner** [comment]
> MLB isn't publishing the feeds. I don't think there's anything I can do for this.

Which feeds aren't being published? Every game still plays fine through the web interface and through [my Node app](https://github.com/tonywagner/mlbserver).

**Comment by tonywagner** [comment]
You can fix this by changing part of line 56 of file mlbv/mlbam/mlbgamedata.py

Change "content(all)" to "content(media(epg))"

Not sure if there is other content needed by other functions in your program, but this will allow fetching the videos again.

**Comment by kmac** [comment]
I'll have to give that a try. I don't have a lot of time to work on this these days though. 

In short, I'm considering mothballing mlbv. There seems to be good alternatives in both streamglob, and now @tonywagner 's https://github.com/tonywagner/mlbserver looks very promising.

I have a couple of reasons I'm losing the energy to maintain this:

- My original reason for creating mlbv was because MLB.tv didn't support linux browsers. I had no way to watch games on my laptop. That's not the case anymore.
- All my Blue Jays games are now blacked out by Sportsnet across Canada. I can't even use their service to watch my team anymore.

I'll probably let this sit a bit over the winter and see where I am in a few months.

**Comment by mkomko** [comment]
@kmac Damn, it sucks that you're now blacked out from your team's games! No wonder you don't feel the motivation to maintain mlbv anymore.

Of course I'd be very sad to see it go, it's definitely the tool that best fits my needs. If you can find the time and energy to keep it going as long as only quick fixes like this are required, that would be awesome. But if not, it's understandable as well, I know how it is. Thanks for everything!

**Comment by kmac** [comment]
Should be fixed in v0.0.19

**Comment by ljcervantes** [comment]
Hi- Was wondering about nhlv.  I am in the states and they switched using
Espn+.  Is there a way to add subscription in the config file?
